services:
  db:
    image: postgres:15
    container_name: cp_db
    environment:
      POSTGRES_DB: cp_crice_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: cp_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cp_crice_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: cp_frontend
    ports:
      - "4200:80" # Mapping Nginx port 80 to 4200 for your convenience
    depends_on:
      - backend